### ISSUE TITLE
Text is blurry on retina displays (with fix)

### ISSUE THREAD

**Issue by CrazyDevil** [dwipp/DPImageGenerator#1]
If you create small images, the text is blurry on retina displays.

I have replaced

```
UIGraphicsBeginImageContext(self.viewBuilder(text).frame.size)
```

with

```
UIGraphicsBeginImageContextWithOptions(self.viewBuilder(text).frame.size, false, UIScreen.mainScreen().scale)
```

in function imageGenerator.

Now the text is clean and sharp on retina displays.

**Comment by dwipp** [comment]
Hi Maik Pütz,

You are the hero! Big thanks from me.
I'll update it soon.
