### ISSUE TITLE
Get always the same color for the same string (with fix - I think can be improved)

### ISSUE THREAD

**Issue by SalvaP** [dwipp/DPImageGenerator#2]
If you need to obtain the same image you can replace

let x = Int(arc4random_uniform(UInt32(color1.count)))
with
srandom(UInt32(text.characters.count))
let x = Int(random()%color1.count)

is based on the length of the string, not the content
It can be implement better and add it as an option, no default

**Comment by dwipp** [comment]
@SalvaP
Nice option! Will be proceed it soon.
Thanks bro.

**Comment by dwipp** [comment]
@SalvaP 

I placed new option for this issue. You could check it in ReadMe.
Thanks!

**Comment by SalvaP** [comment]
Thank you!
I thought I'd calculate the seed taking into account the contents of the string by replacing
            srandom(UInt32(text.characters.count))
with
            srandom(UInt32(abs(text.hashValue)%1000))

takes the last 3 numbers of the  |hashValue|

.hashValue can be replaced with .hash (should be used the one that takes less resource to be calculate but i don't know which is)
%1000 can be at max  %1000000000 in my tests (but 3 to 5 digits shoud be enough)
always can be simpler/improved
